steps:
# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['test']

- name: 'gcr.io/cloud-builders/docker'  
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker' 
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'sample-app.deployment-service.yaml']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - [DEPLOYMENT-NAME]
  - [CONTAINER]=gcr.io/[PROJECT-ID]/[IMAGE]:[TAG]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=[COMPUTE-ZONE]'
  - 'CLOUDSDK_CONTAINER_CLUSTER=[CLUSTER]'