steps:
# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['$BUILD_ID']

# - name: 'gcr.io/cloud-builders/docker'  
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/image', '.']

# - name: 'gcr.io/cloud-builders/docker' 
#   args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']
steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/image:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/image:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/image:latest',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/image:latest']
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'sample-app.$_DEPLOYMENT.yaml']

# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=gcr.io/$PROJECT_ID/image:latest'
#   - --cache=true
#   - --cache-ttl=6h
# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#   - 'apply'
#   - '--filename=sample-app.deployment-service.yml'
#   env:
#     - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
#     - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#     - set
#     - image
#     # - deployment
#     - deployment/sample-app
#     - sample-app=gcr.io/$PROJECT_ID/image
#   env:
#     - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
#     - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

# images: ['gcr.io/$PROJECT_ID/image']

# - name: gcr.io/k8s-skaffold/skaffold
  # args: ['skaffold', 'run', '-f', 'skaffold.yaml']
  # args: ['skaffold', 'run']
  # args: ['run', '-p', 'gcb']
  # env:
  # - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
  # - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'