steps:
# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['test']

- name: 'gcr.io/cloud-builders/docker'  
  args: ["build", "-t", "gcr.io/ancient-vortex-243611/sample-app:$REVISION_ID", "."]

- name: 'gcr.io/cloud-builders/docker' 
  args: ["push", "gcr.io/ancient-vortex-243611/sample-app:$REVISION_ID"]
  
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
    - 'set' 
    - 'image' 
    - 'sample-app.deployment-service' 
    - 'sample-app=gcr.io/ancient-vortex-243611/image:$REVISION_ID' 
  # env: 
  #   - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b' 
  #   - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'