steps:
# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'  
#   args: ['test']

# - name: 'gcr.io/cloud-builders/docker'  
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder', '--target', 'builder', '.']

# - name: 'gcr.io/cloud-builders/docker' 
#   args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder']

- name: 'gcr.io/cloud-builders/docker'  
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker' 
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'sample-app.$_DEPLOYMENT.yaml']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    # - deployment
    - deployment/sample-app
    - sample-app=gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'