apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: gcr.io/ancient-vortex-243611/sample-app@sha256:fbefc5ca062b42c5ea4eb6669d5c4e5921f848b828cf8f62c76bc03591bb7aa9 #this is where to make your changes
          env:
            - name: APP_NAME
              value: "sample-app"
            - name: TEST_ME
              value: "Hello, world!"
            - name: PORT
              value: "4444"
          ports:
            - containerPort: 4444
              name: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: sample-app
  selector:
    app: sample-app