apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/ancient-vortex-243611/image:latest
    context: .
deploy:
  kubectl:
    manifests:
    - sample-app.deployment-service.yml
# profiles : 
#   - name : gcb 
#     build : 
#       googleCloudBuild : 
#         projectId : ancient-vortex-243611
